/**
 * fix_all_tools_ui.js
 */

const fs = require('fs');
const path = require('path');

const componentsDir = path.join(__dirname, 'frontend', 'components');

function getAllClientFiles(dir) {
  const results = [];
  const items = fs.readdirSync(dir, { withFileTypes: true });
  for (const item of items) {
    const fullPath = path.join(dir, item.name);
    if (item.isDirectory()) {
      results.push(...getAllClientFiles(fullPath));
    } else if (item.name.endsWith('Client.tsx')) {
      results.push(fullPath);
    }
  }
  return results;
}

const files = getAllClientFiles(componentsDir);

const badgeHtml = `<div className="hidden sm:flex items-center gap-2 px-3 py-1.5 bg-[#EEF2FF] text-[#6366F1] rounded-lg text-sm font-medium"><History className="w-4 h-4" /> Your creations are saved in history</div>`;

let updatedCount = 0;

for (const file of files) {
  if (file.includes('ImageGenerator') || file.includes('BackgroundRemover') || file.includes('AiAdCopy')) continue;

  let content = fs.readFileSync(file, 'utf-8');
  let originalContent = content;

  // 1. Replace the inner history button (the one with span hidden sm:inline)
  const innerHistoryButtonRegex = /<button[^>]*>\s*<History[^>]*\/>\s*<span className="hidden sm:inline">History<\/span>\s*<\/button>/;
  if (innerHistoryButtonRegex.test(content)) {
    content = content.replace(innerHistoryButtonRegex, badgeHtml);
  }

  // 2. Change (result || isProcessing) to (result) for the Result Header
  content = content.replace(/\{\(result \|\| isProcessing\) && \(/g, '{result && (');

  // 3. For Pattern B and Premium tools: inject isProcessing check around the result area
  // We look for the main white box div
  const whiteBoxDiv = /<div className="flex-grow bg-white border border-\[#E5E7EB\] rounded-3xl p-6 lg:p-8 shadow-sm flex flex-col h-\[600px\] animate-in fade-in slide-in-from-bottom-4 duration-500 fill-mode-both delay-150">/;
  
  // Wait, if it already has `isProcessing ?` we need to be careful.
  // The premium tools generated by me have:
  // `) : !result && !isProcessing ? (`
  // AND
  // `) : (`
  // wait, the premium tools look like this:
  // <div className="flex-grow bg-white ...">
  //   {showHistory ? ( ... ) : !result && !isProcessing ? ( ... Ready to gen ... ) : ( <div ... > ... Result Header ... {result ? ... : <TextGenerationProgress>} </div> )}
  
  // In Premium tools (Pattern C), TextGenerationProgress is already there but inside the result box!
  // In Pattern B tools (AiElevatorPitch), there is NO TextGenerationProgress and NO isProcessing check in the box!
  
  // Let's standardize them.
  // Instead of complex regex, I will just manually regenerate the Premium Tools because I can easily change generate_premium_tools.js!
  
  // What about the 20 Pattern B files?
  // Let's identify Pattern B files: They don't have TextGenerationProgress yet.
  if (!content.includes('TextGenerationProgress') && whiteBoxDiv.test(content)) {
    // Pattern B file
    // We want to replace the inside of the white box.
    // The white box has:
    // {/* Result Header */}
    // {result && ( ... )}
    // <div className="flex-grow overflow-y-auto custom-scrollbar pr-2">
    //   {result ? ( ... ) : ( ... Ready to generate ... )}
    // </div>
    // 
    // We will wrap everything inside the white box (after the div) with:
    // {isProcessing ? <TextGenerationProgress title="Generating Content..." description="Crafting your response." /> : ( <> ... </> )}
    
    // Split content by the whiteBoxDiv
    const parts = content.split(whiteBoxDiv);
    if (parts.length === 2) {
      // Find the matching closing div for the white box.
      // It's just the last `</div>` before `</main>`.
      // Actually, since we know the structure:
      // whiteBoxDiv
      // ... content ...
      // </div>
      // </main>
      
      let innerContent = parts[1];
      // Replace the last </div>\n        </main> with just closing tags
      innerContent = innerContent.replace(/<\/div>\s*<\/main>\s*\}\)\s*<\/div>\s*;\s*\}\s*$/, ''); // this is too fragile
      
      // Let's just do a regex replace on the block
      content = content.replace(
        /(<div className="flex-grow bg-white border border-\[#E5E7EB\] rounded-3xl p-6 lg:p-8 shadow-sm flex flex-col h-\[600px\] animate-in fade-in slide-in-from-bottom-4 duration-500 fill-mode-both delay-150">)([\s\S]*?)(<\/div>\s*<\/main>)/,
        (match, open, inner, close) => {
          return `${open}\n          {isProcessing ? (\n            <TextGenerationProgress title="Generating Content..." description="Crafting your response." />\n          ) : (\n            <>\n${inner}            </>\n          )}\n        ${close}`;
        }
      );
      
      // Add import
      if (!content.includes('TextGenerationProgress')) {
        const lastImportMatch = [...content.matchAll(/^import .*;$/gm)].pop();
        if (lastImportMatch) {
          const insertPos = lastImportMatch.index + lastImportMatch[0].length;
          content = content.slice(0, insertPos) + '\nimport TextGenerationProgress from \'../shared/TextGenerationProgress\';' + content.slice(insertPos);
        }
      }
    }
  }

  // 4. Also fix Pattern A files (like AiCodeExplainerClient.tsx)
  // Pattern A files ALREADY have TextGenerationProgress (from my previous script update_results_ui.js)
  // But they might have the inner History button still if my previous regex missed it.
  
  if (content !== originalContent) {
    fs.writeFileSync(file, content, 'utf-8');
    updatedCount++;
    console.log(`Fixed ${path.basename(file)}`);
  }
}

console.log(`Done fixing ${updatedCount} files.`);
